name: Build Android APK

on:
  push:
    paths:
      - 'app_adr/**'
      - '.github/workflows/build_apk.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build APK with Gradle
        run: |
          cd app_adr
          gradle assembleRelease --no-daemon -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=1024m"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VietCalendar-Android-APK
          path: app_adr/app/build/outputs/apk/release/*.apk
